### ISSUE TITLE
Could not read WebJar RequireJS config for: highstock 4.2.4

### ISSUE THREAD

**Issue by amaury-d** [webjars/highstock#19]
Hello,

The requirejs JS for this package should be added.

Best regards.

**Comment by jamesward** [comment]
This will be released shortly as `4.2.5-1`.

**Comment by amaury-d** [comment]
Thanks!

On Tue, May 10, 2016 at 4:56 PM, James Ward <notifications@github.com>
wrote:

> This will be released shortly as 4.2.5-1.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/webjars/highstock/issues/19#issuecomment-218183761>
>



-- 
Amaury Decrême
