### ISSUE TITLE
Incorrect version number (#2)

### ISSUE THREAD

**Issue by markot6** [webjars/highstock#22]
After the 4.2.6 Highstock webjar is pulled into the ".m2/repository/org/webjars/highstock" directory, the version directory inside the webjar is still named "${highstock.version}" instead of "4.2.6", despite a fix to issue #21, even if the previous ".m2/repository/org/webjars/highstock/4.2.6" directory was deleted prior to the download.

**Comment by jamesward** [comment]
You need to use the new `4.2.6-1` version.
