### ISSUE TITLE
Webjar for Higstock 5.0.4 incorrectly contains Highcharts 5.0.4

### ISSUE THREAD

**Issue by markot6** [webjars/highstock#28]
See the contents of:
    highstock-5.0.4.jar/META-INF/resources/webjars/highstock/5.0.4/highstock,js
Its header comment reads:
/*
 Highcharts JS v5.0.4 (2016-11-22)
 (c) 2009-2016 Torstein Honsi
 License: www.highcharts.com/license
*/
Compare to the contents of 5.0.3.

**Comment by jamesward** [comment]
We just repackage the upstream stuff so this mush come from them.
