### ISSUE TITLE
8.0.4

### ISSUE THREAD

**Issue by niksmet** [webjars/highstock#42]

**Comment by jamesward** [comment]
That release doesn't exist: https://github.com/highcharts/highstock-release/releases

**Comment by niksmet** [comment]
https://www.highcharts.com/blog/download/
Latest release is 8.0.4.

**Comment by jamesward** [comment]
Oh right, they merged highstock into highcharts.  And that release already exists in the highcharts WebJar.

**Comment by jamesward** [comment]
Oh wait.  They do still have a highstock distribution it just isn't on the highstock github anymore.
